### ISSUE TITLE
Take Down Your Code

### ISSUE THREAD

**Issue by LeozaCEO2** [r3a1ty/Best-Blooket-Hacks#2]
You will be sent a DMCA takedown.

**Comment by LeozaCEO2** [comment]
Minesraft2 Blooket Cheats Licence:[https://github.com/Minesraft2/Blooket-Cheats/blob/main/LICENSE](url)

**Comment by r3a1ty** [comment]
Okay here the deal if i doing this for my school friends! we always play blooket so please notify me back u take credit i dont take credit

**Comment by r3a1ty** [comment]
if u dont say deal i'll take it down

**Comment by r3a1ty** [comment]
i ment was U take CREDIT i dont get anything

**Comment by LeozaCEO2** [comment]
what's the deal?

**Comment by LeozaCEO2** [comment]
If you take it down, then you won't be subject to legal action.

**Comment by r3a1ty** [comment]
u take credit I dont problem solve

**Comment by r3a1ty** [comment]
i just took it down

**Comment by LeozaCEO2** [comment]
Ok, you're good. Thank you for your cooperation.
