### ISSUE TITLE
DELETE THIS NOW

### ISSUE THREAD

**Issue by Kaedawg** [r3a1ty/Best-Blooket-Hacks#5]
YOU SAID U TOOK IT DOWN. ITS BACK UP.. @r3a1ty @Minesraft2

**Comment by Minesraft2** [comment]
Yea take this down by tmr or else I'll submit a dmca

**Comment by Minesraft2** [comment]
mb I forgot, I'll start submitting the dmca now

**Comment by Minesraft2** [comment]
![image](https://github.com/r3a1ty/Best-Blooket-Hacks/assets/49218878/c525978d-28c2-4564-8822-856b62cdd7c4)

**Comment by r3a1ty** [comment]
@Kaedawg its back lmaoooo

**Comment by r3a1ty** [comment]
i have full ownership now!!

**Comment by Kaedawg** [comment]
@ghost

**Comment by Kaedawg** [comment]
> i have full ownership now!!

no you dont his account just got deleted

**Comment by Kaedawg** [comment]
that doesnt mean you own the code

**Comment by Kaedawg** [comment]
take it down or ill DMCA it for him

**Comment by r3a1ty** [comment]
the thing is the code does not exist anymore.

**Comment by r3a1ty** [comment]
and still i own it most of his hax does not work anymore
